import PostList from "@/components/PostList";
import { PostType } from "@/utils/sharedType";
import axios from "axios";
import Head from "next/head";
import styles from "../styles/Home.module.scss";

export default function Home({ postList }: { postList: PostType[] }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostList postList={postList} />
    </div>
  );
}

export const getServerSideProps = async () => {
  const res = await axios.get("http://localhost:3000/api/post");
  return {
    props: { postList: res?.data?.postList },
  };
};
